# Generated by Django 3.2.5 on 2021-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledstat',
            name='status',
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led1_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led2_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='led3_status',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
