# Generated by Django 3.0.2 on 2021-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0002_auto_20211115_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledstat',
            name='temprature',
            field=models.FloatField(default=0),
        ),
    ]
