# Generated by Django 3.0.2 on 2021-11-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0003_ledstat_temprature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledstat',
            name='temprature',
            field=models.IntegerField(default=0),
        ),
    ]
