# Generated by Django 4.0 on 2022-01-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspi', '0006_userdevices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledstat',
            name='imp_1',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='imp_2',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='ledstat',
            name='imp_3',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='userdevices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
